### ISSUE TITLE
Implementing concepts from Docusaurus - Full MD Support

### ISSUE THREAD

**Issue by batunpc** [batunpc/palpatine#14]
[Docusaurus](https://docusaurus.io/docs/) has so many cool features an SSG could have. Some of the potential features could be implemented for palpatine;

- Search Engine Optimization (SEO), including `meta` tags in the HTML head
- Improved Accessibility of generated HTML
- Support for React components
- [Themes](https://docusaurus.io/docs/using-themes)
- [Plugins](https://docusaurus.io/docs/using-plugins)
- Configurable [Sidebar](https://docusaurus.io/docs/sidebar) (i.e., table of contents)
- Full Markdown support (e.g., swap out your basic version for an open source library/module that does it fully)
- Syntax Highlighting for code blocks
- Search
- [Static Assets](https://docusaurus.io/docs/static-assets#referencing-your-static-asset) for images, stylesheets, etc.
- [Markdown Frontmatter](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#markdown-frontmatter) support
- Blog posts in addition to Pages

While I want to implement all these features currently my goal is to implement `Full Markdown support`. I found an library [maddy](https://github.com/progsource/maddy) that handles MD to HTML parsing. Syntax highlighting might be good addition.

### Tasks - Full MD Support

- [x] Use [maddy](https://github.com/progsource/maddy) parser library.
- [x] Update dataset & docs.
- [x] Deploy to netlify

**Comment by batunpc** [comment]
### Tasks - Full MD Support

- [ ] Use [maddy](https://github.com/progsource/maddy) parser library.
- [ ] Update dataset & docs.
- [ ] Deploy to netlify

**Comment by batunpc** [comment]
Squashed commit https://github.com/batunpc/palpatine/commit/15cec061d28787c15affd477098e97d065a1c8fb
